apiVersion : apps/v1
kind: Deployment
metadata:
  name: wasimjenkinswithdockercomposeup 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasimjenkinswithdockercomposeup
  template:
    metadata:
      labels:
        app: wasimjenkinswithdockercomposeup
    spec:
      containers:
        - name: wasimjenkinswithdockercomposeup 
          image: dotnetacrlatest.azurecr.io/dotnetacrlatest:777
          #dotnetacrlatest.azurecr.io/jaganrajagopaljenkinswithdockercomposeup
          #just comments
          #dotnetacrv1.azurecr.io/jaganrajagopaljenkinswithdockercomposeup
          ports:
          - containerPort: 80
